import WZManager from '../wz-utils/WZManager';
import { cachedFetch } from '../AssetDownloader';
import MapleInventory from '../Constants/Inventory/MapleInventory';
import { getEquipWzPath } from '../Inventory/Item';

/**
 * Static Monster Book catalogue — the 343 v83 monster cards and the monster
 * each one describes.
 *
 * `/data/monsterbook.json` is generated by `tools/build-monsterbook-data.js`
 * straight out of the WZ (see that file for the exact source nodes). It exists
 * because the per-monster stats live in Mob.wz, which averages 620KB an entry,
 * peaks at 31MB, and is evicted from the WZ cache on every map change — the
 * book would stall the game loop pulling those in to fill a stat line.
 *
 * Names are NOT in the generated file: monster, map and item names all resolve
 * through the String.wz tables the rest of the UI already shares.
 */

/** Cards a page of the book holds (the cardSlot art is a 5x5 grid). */
export const CARDS_PER_PAGE = 25;

/** Copies of one card the book will hold. The 5th completes it. */
export const MAX_COPIES = 5;

/**
 * The nine left-hand tabs, in WZ order. v83 groups cards by the monster's
 * level, one tab per 15 levels, with everything unusual in a ninth tab: card
 * id 2380xxx is the level 1-15 tab, 2387xxx is 105+, and 2388xxx is SPECIAL
 * (bosses and event monsters). Verified against Mob.wz — every 2380xxx card
 * points at a level 1-15 monster, every 2381xxx card at a level 17-30 one, and
 * so on, while 2388xxx spans levels 10 to 180.
 */
export const TAB_LABELS = [
  'Lv. 1 ~ 15',
  'Lv. 16 ~ 30',
  'Lv. 31 ~ 45',
  'Lv. 46 ~ 60',
  'Lv. 61 ~ 75',
  'Lv. 76 ~ 90',
  'Lv. 91 ~ 105',
  // The 2387xxx block actually spans levels 106-131; the footer has no room
  // for "and up" beside the pager
  'Lv. 106 +',
  'Special',
];

export const TAB_COUNT = TAB_LABELS.length;

/** The tab whose cards count as "special" rather than "basic". */
export const SPECIAL_TAB = 8;

export interface MonsterBookCard {
  /** Item id, 2380000-2388070 */
  id: number;
  /** The monster this card describes */
  mob: number;
}

export interface MonsterBookMob {
  lv: number;
  hp: number;
  mp: number;
  exp: number;
  pad: number;
  pdd: number;
  mad: number;
  mdd: number;
  acc: number;
  eva: number;
  boss: number;
  undead: number;
  /** "Mammal", "Plant", ... — from the episode text's Form line */
  form: string;
  /** "Resistant to Poison Attribute Attacks." and friends, may be empty */
  trait: string;
  /** The episode paragraph shown on the EPISODE tab */
  lore: string;
  /** Maps the monster spawns on — the FOUND IN tab */
  maps: number[];
  /** Items the monster drops — the DROPPING tab */
  rewards: number[];
}

interface MonsterBookFile {
  cards: MonsterBookCard[];
  mobs: Record<string, MonsterBookMob>;
}

const EMPTY_MOB: MonsterBookMob = {
  lv: 0, hp: 0, mp: 0, exp: 0, pad: 0, pdd: 0, mad: 0, mdd: 0, acc: 0, eva: 0,
  boss: 0, undead: 0, form: '', trait: '', lore: '', maps: [], rewards: [],
};

let file: MonsterBookFile | null = null;
let loadPromise: Promise<void> | null = null;

/** cards grouped by tab, each already sorted by card id (page/slot order) */
let byTab: MonsterBookCard[][] = [];
const byId = new Map<number, MonsterBookCard>();
const byMob = new Map<number, MonsterBookCard>();

/**
 * Promise-cached, like QuestData's name tables: a flag would let a second
 * caller past the guard while the fetch is still in flight and hand it an
 * empty catalogue, and a failed fetch would poison the flag for the session.
 */
export function ensureMonsterBookData(): Promise<void> {
  if (!loadPromise) {
    loadPromise = (async () => {
      const resp = await cachedFetch('/data/monsterbook.json');
      const data: MonsterBookFile = await resp.json();
      file = data;
      byTab = Array.from({ length: TAB_COUNT }, () => [] as MonsterBookCard[]);
      for (const card of data.cards) {
        byId.set(card.id, card);
        byMob.set(card.mob, card);
        const tab = tabOf(card.id);
        if (tab >= 0 && tab < TAB_COUNT) byTab[tab].push(card);
      }
      for (const list of byTab) list.sort((a, b) => a.id - b.id);
      console.log(
        `[MonsterBook] ${data.cards.length} cards across ${TAB_COUNT} tabs`
      );
    })().catch((e) => {
      console.error('[MonsterBook] catalogue load failed, will retry:', e);
      loadPromise = null;
    }) as Promise<void>;
  }
  return loadPromise;
}

/** Which left-hand tab a card belongs to (2380xxx -> 0 ... 2388xxx -> 8) */
export function tabOf(cardId: number): number {
  return Math.floor(cardId / 1000) - 2380;
}

/** Special cards are the 2388xxx block — bosses and event monsters. */
export function isSpecialCard(cardId: number): boolean {
  return Math.floor(cardId / 1000) >= 2388;
}

/** Whether an item id is one of the 343 monster cards. */
export function isMonsterCard(itemId: number): boolean {
  return byId.has(itemId);
}

/**
 * Cheap range test for callers that may run before the catalogue has loaded
 * (the drop pickup path). The card block is 2380000-2388999 and holds nothing
 * else in v83.
 */
export function isMonsterCardId(itemId: number): boolean {
  return itemId >= 2380000 && itemId <= 2388999;
}

export function getCard(cardId: number): MonsterBookCard | undefined {
  return byId.get(cardId);
}

export function getCardForMob(mobId: number): MonsterBookCard | undefined {
  return byMob.get(mobId);
}

export function getCardsForTab(tab: number): MonsterBookCard[] {
  return byTab[tab] ?? [];
}

export function getAllCards(): MonsterBookCard[] {
  return file?.cards ?? [];
}

export function getMobInfo(mobId: number): MonsterBookMob {
  return file?.mobs?.[String(mobId)] ?? EMPTY_MOB;
}

/** Pages a tab needs at 25 cards a page (at least one, so it never draws empty) */
export function pageCount(tab: number): number {
  return Math.max(1, Math.ceil(getCardsForTab(tab).length / CARDS_PER_PAGE));
}

// ---- card art ------------------------------------------------------------

const iconCache = new Map<number, HTMLImageElement | null>();
const iconPending = new Set<number>();

/**
 * The card's face, 27x38 — exactly the size of a cardSlot hole.
 *
 * `iconRaw` is the un-cropped art (`icon` is the 32x32 inventory version with
 * its own padding), so it lines up with the slot without any fitting. Returns
 * null until the WZ file has parsed; the draw pass simply skips the frame and
 * picks it up next time round rather than blocking on it.
 */
export function getCardIcon(cardId: number): HTMLImageElement | null {
  const cached = iconCache.get(cardId);
  if (cached !== undefined) return cached;
  if (iconPending.has(cardId)) return null;
  iconPending.add(cardId);
  const padded = String(cardId).padStart(8, '0');
  WZManager.get(`Item.wz/Consume/0238.img/${padded}/info/iconRaw`)
    .then((node: any) => {
      iconCache.set(cardId, node?.nGetImage?.() ?? null);
    })
    .catch(() => {
      iconCache.set(cardId, null);
    })
    .finally(() => {
      iconPending.delete(cardId);
    });
  return null;
}

/**
 * Warm every card face in one tab. The whole 0238.img is a single 1.3MB file,
 * so this costs one parse for all 343 and keeps the grid from filling in
 * sprite by sprite as the images decode.
 */
export function preloadTabIcons(tab: number): void {
  for (const card of getCardsForTab(tab)) getCardIcon(card.id);
}

// ---- reward item icons ---------------------------------------------------

const itemIconCache = new Map<number, HTMLImageElement | null>();
const itemIconPending = new Set<number>();

/**
 * Icon for an item on the DROPPING list.
 *
 * Equips (category 1) keep their art in Character.wz rather than Item.wz, so
 * the path comes from the same helper the inventory uses; `iconRaw` is
 * preferred there because the 32x32 `icon` is padded for the item slot.
 */
export function getRewardIcon(itemId: number): HTMLImageElement | null {
  const cached = itemIconCache.get(itemId);
  if (cached !== undefined) return cached;
  if (itemIconPending.has(itemId)) return null;
  itemIconPending.add(itemId);

  const finish = (node: any) => {
    const info = node?.info;
    const canvasNode = info?.iconRaw?.nTagName === 'canvas' ? info.iconRaw : info?.icon;
    itemIconCache.set(itemId, canvasNode?.nGetImage?.() ?? null);
  };

  const equipPath = getEquipWzPath(itemId);
  const padded = String(itemId).padStart(8, '0');
  const path = equipPath
    ? equipPath
    : (() => {
        const wzType = MapleInventory.getWzNameFromInventoryId(padded);
        if (!wzType) return null;
        if (wzType === MapleInventory.WzInventoryType.Pet) {
          return `Item.wz/Pet/${itemId}.img`;
        }
        return `Item.wz/${wzType}/${padded.slice(0, 4)}.img/${padded}`;
      })();

  if (!path) {
    itemIconCache.set(itemId, null);
    itemIconPending.delete(itemId);
    return null;
  }

  WZManager.get(path)
    .then(finish)
    .catch(() => {
      itemIconCache.set(itemId, null);
    })
    .finally(() => {
      itemIconPending.delete(itemId);
    });
  return null;
}

// ---- monster names -------------------------------------------------------

const mobNames = new Map<number, string>();
let mobNamesPromise: Promise<void> | null = null;

/**
 * Monster names from String.wz/Mob.img — the same table the damage numbers and
 * quest text read. Promise-cached for the reason QuestData spells out: a flag
 * would let the search box resolve against a half-filled table.
 */
export function ensureMobNames(): Promise<void> {
  if (!mobNamesPromise) {
    mobNamesPromise = (async () => {
      const node: any = await WZManager.get('String.wz/Mob.img');
      for (const mob of node?.nChildren ?? []) {
        const id = parseInt(mob.nName, 10);
        if (!Number.isFinite(id)) continue;
        const name = mob.nGet?.('name')?.nValue;
        if (name) mobNames.set(id, String(name));
      }
    })().catch((e) => {
      console.error('[MonsterBook] monster name load failed, will retry:', e);
      mobNamesPromise = null;
    }) as Promise<void>;
  }
  return mobNamesPromise;
}

export function getMobName(mobId: number): string {
  return mobNames.get(mobId) || `Monster ${mobId}`;
}

/**
 * First card whose monster name contains `query`, searched in book order so
 * the low-level tabs answer before the special one. Returns null on no match.
 */
export function findCardByName(query: string): MonsterBookCard | null {
  const needle = query.trim().toLowerCase();
  if (!needle) return null;
  for (let tab = 0; tab < TAB_COUNT; tab++) {
    for (const card of getCardsForTab(tab)) {
      if (getMobName(card.mob).toLowerCase().includes(needle)) return card;
    }
  }
  return null;
}
