/**
 * Custom WZ overlay — assets of our own (Roni's Developer Throne) grafted
 * into the converted WZ tree at load time, so every consumer (Item.load,
 * sitOnChair, icons, tooltips, remote seats) sees them exactly like
 * Nexon-shipped nodes and nothing else has to know they are special.
 *
 * Source of truth: /data/custom-items.json (generated by
 * tools/custom-assets/*.py), keyed by the .img path the nodes belong under:
 *   { "wz": { "Item.wz/Install/0301.img": [ <$imgdir node>, ... ] },
 *     "names": { "<itemId>": { "name", "desc" } } }
 * Kept out of the converted JSON so a WZ reconvert cannot drop them.
 */
import WZNode from './wz-utils/WZNode';

type Overlay = { wz?: Record<string, any[]>; names?: Record<string, { name: string; desc?: string }> };

let overlayPromise: Promise<Overlay> | null = null;

export function loadCustomOverlay(): Promise<Overlay> {
  if (!overlayPromise) {
    overlayPromise = (async () => {
      try {
        const { cachedFetch } = await import('./AssetDownloader');
        const res = await cachedFetch('/data/custom-items.json');
        if (!res.ok) return {};
        return (await res.json()) as Overlay;
      } catch {
        return {};
      }
    })();
  }
  return overlayPromise;
}

/** Graft this file's custom children onto its freshly loaded subtree. */
export async function graftCustomNodes(filename: string, subtree: any): Promise<void> {
  const overlay = await loadCustomOverlay();
  const nodes = overlay.wz?.[filename];
  if (!nodes?.length || !subtree) return;
  for (const json of nodes) {
    const node = new WZNode(json, subtree);
    const existing = subtree.nChildren.findIndex((c: any) => c.nName === node.nName);
    if (existing !== -1) subtree.nChildren.splice(existing, 1);
    subtree[node.nName] = node;
    subtree.nChildren.push(node);
  }
}

/** Custom item names/descriptions, merged into the String.wz tables. */
export async function customItemNames(): Promise<Record<string, { name: string; desc?: string }>> {
  return (await loadCustomOverlay()).names ?? {};
}

/** Items only the superuser may use (`info/devOnly`). */
export function isDevOnlyNode(node: any): boolean {
  return !!(node?.info?.devOnly?.nValue ?? node?.nGet?.('info')?.nGet?.('devOnly')?.nValue);
}
